[package]
name = "simple-bupt-report"
version = "0.1.1"
entrypoint = "lib.typ"
authors = ["April <@zhao-leo>"]
license = "MIT"
description = "一份简单的北邮实验报告模板 Simple BUPT Report"
repository = "https://github.com/JackyLee3362/simple-ecnu-thesis"
keywords = ["homework", "report", "university", "bupt"]
categories = ["report"]
exclude = ["template/main.pdf",".gitignore"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"